### ISSUE TITLE
Pressing backspace anywhere on page open pickpocket window

### ISSUE THREAD

**Issue by scalp42** [canisbos/Pickpocket#7]
Pickpocket looks nice but unfortunately every time you press backspace, the main extension window open preventing you from erasing anything in a field.

**Comment by canisbos** [comment]
Did you perhaps set your Pickpocket hot key to Backspace?

**Comment by scalp42** [comment]
I actually tried to clear the default hot key by pressing Backspace. It doesn't show any shortcut but that might be why 😆

**Comment by scalp42** [comment]
Closing as restoring the default and disabling/reenabling the plugin worked.

Thanks for the extension!

**Comment by canisbos** [comment]
Glad to hear it.
